### PR TITLE
feat: Add Grafana dashboards for the Simulator

### LINKED ISSUE #379: Resolve Prometheus issues in the Simulator
As a simulator operator
I want to be able to track metrics using Proemetheus and display them in Grafana.
So that I can better understand the gaps in the application

### Additional Information
We already have a metrics service, which we are using in the Simulator. Prometheus is not enabled due to some port conflicts with block-node, which has to be resolved.

### PR DESCRIPTION
**Pull request by georgi-l95**
**Description**:
This PR adds Grafana dashboards for monitoring the Block Stream Simulator in both Publisher and Consumer modes, along with the necessary Prometheus configuration to support metric collection.

* Add Grafana dashboards for Publisher and Consumer metrics
* Update Prometheus configuration to differentiate metrics by instance type
* Add metrics documentation to simulator quickstart guide

**Related issue(s)**:

Fixes #379 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by ata-nas — COMMENTED** [review]
Looks good on first glance, some files do not end with a newline character however, would suggest to add that on the missing files.

**Comment by ata-nas** [comment]
> @ata-nas Which ones, I don't see it. 🤔 Could be wrong of course, I though I added to all of them.

Hmm. You have indeed added newlines. GitHub however does not want to show that... sorry, mb :)

**Review by ata-nas — APPROVED** [review]
LGTM @georgi-l95

**Review by AlfredoG87 — APPROVED** [review]
LGTM 👍

**Pull request merged**
